### ISSUE TITLE
change login url

### ISSUE THREAD

**Issue by domdinicola** [unicef/drips-fe#3]
change current login url with `drips/social/login/unicef-azuread-tenant-oauth2/`

**Comment by danNordlogic** [comment]
Fixed with https://github.com/unicef/drips-fe/pull/5

**Comment by ntrncic** [comment]
> Fixed with #5

@danNordlogic still the issue is there. how about changing this  <Link href="/sociallogin/unicef-azuread-b2c-oauth2/">Sign In</Link> on the page?
